### ISSUE TITLE
If i want to load a imageview instead of a drawable?

### ISSUE THREAD

**Issue by sddesigns7** [SeptiyanAndika/Camera-Overlay-Android#1]
Hi! awesome! I want to draw a imageview thats on my screen instad of a drawable. how do i change this part?

```
       Drawable drawable = getResources().getDrawable
                (R.mipmap.ic_launcher);
        drawable.setBounds(20, 30, drawable.getIntrinsicWidth()+20, drawable.getIntrinsicHeight()+30);
        drawable.draw(canvas);
```

i want it to load a imageview

```
        ImageView thisisImg= (ImageView)findViewById(R.id.ImageView01);
```

**Comment by SeptiyanAndika** [comment]
hi @sddesigns7 , you must convert imageview to drawable, you can use getDrawable method in imageview, because method draw not accpet imageview.
 
https://developer.android.com/reference/android/widget/ImageView.html#getDrawable().

thanks
