### ISSUE TITLE
Unable to import this project in android studio

### ISSUE THREAD

**Issue by Rajendra03dec** [SeptiyanAndika/Camera-Overlay-Android#2]
Hi , I have downloaded this sample code but when trying to import in android studio its throwing an error

Refer Screen sort
![capture](https://user-images.githubusercontent.com/7902926/28255749-97121c4a-6ad8-11e7-93c4-27a7aa3d5941.PNG)

**Comment by SeptiyanAndika** [comment]
Hi @Rajendra03dec this project still using eclipse, will try migrate to android studio if have a time. thanks

**Comment by bharath989** [comment]
Can you please change this code for Android Studio...

**Comment by SeptiyanAndika** [comment]
@bharath989 @Rajendra03dec really sorry i not maintenance again this repo, for run thats project in android studio you can copy mainActivity.java and resource to android studio projects. and update permisiion in android.xml

Thanks.
