### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by sermarr** [SeptiyanAndika/Camera-Overlay-Android#3]
This object:

private Camera camera = null

is always null and is never created, so you get...

java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
        at com.example.smarrero.myapplication.MainActivity.surfaceChanged(MainActivity.java:179)

Apart from the not working on Android Studio problem described in another issue.

**Comment by SeptiyanAndika** [comment]
Sorry @sermarr now this repo unmaintained
